### ISSUE TITLE
Korina

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#25]
## Korina

Dataset link: www.korina.info

Region: Germany, Saxony-Anhalt State

Taxon: Invasive alien plants

Type: sampling event

Why is this important: Citizen science initiative documenting the presence and absence of invasive alien plants in Sachsen-Anhalt State, Germany. IAS is a topical subject that needs attention.

License: CC-BY-NC 4.0

Comments: Kyle Copas met with Katrin Schneider, 8 Feb 2017, at the joint [COST-JRC Workshop] (http://www.cost.eu/events/ias2017), Brussels where she requested for assistance in mapping and formatting Korina data for publication to GBIF. License selection above inferred from the interpretation of the copyright - http://www.korina.info/?q=node/82. Kyle B to contact GBIF Germany to provide Kotrina with the needed assistance

Dataholders contact information: Katrin Lena Schneider, katrin.schneider@ufu.de, www.korina.info &gt;www.ufu.de

Users contact info: siromasinde@gbif.org

**Comment by kcopas** [comment]
Thanks, Siro—didn't know you were entering it and was just starting to myself!

**Comment by kbraak** [comment]
Hi @jholetschek 

I'd like to bring your attention to the following data mobilization target from Germany. The publisher Katrin Scheider has expressed interest in sharing their invasive alien species through GBIF, would you be able to assist her please? 

I have added you as a contributor to this GitHub repository repository. If you are able to provide assistance, please assign this issue to yourself and indicate that mobilization is in progress on the [project management page](https://github.com/gbif/data-mobilization/projects/1).

This is a new experimental workflow for distributed mobilization of content in the GBIF network. If it's successful, we may try to enlist help from other nodes in a similar way. Thanks.

**Comment by jholetschek** [comment]
Just had an extended phone call with Katrin Schneider. Currently Korina does have a database of ~80,000 sightings of invasive species (MySQL, apparently only one single table). About 65,000 are owned by the Landesamt für Umweltschutz and are probably already fed to the Umweltbundesamt, so they might be contained in one of the two datasets provided by **http://www.gbif.org/publisher/43cab2b0-0653-11d9-acb2-b8a03c50a862**. Katrin Schneider will discuss that with Umweltbundesamt prior to a publication in order to avoid duplication.

For some of the sightings, there might an attached absence flags, meaning that the population reported by a sighting is not present any more. As long as GBIF does not support absence data, these sightings should be exempt from publication.

I've sent links about publishing procedures in Germany, ABCD and BioCASe to Katrin for information, who will be in contact with me later.

**Comment by mdoering** [comment]
See gbif/portal16#308 for handling absence data in GBIF

**Comment by jholetschek** [comment]
Phone call with Florian Thürkow from Korina. They will have another shoot at getting the data into GBIF. They do have an own web server running that could be used for BioCASe, Florian will have a look at the documentation and start working on this. The database doesn't have GUIDs yet, but they do consider introducing them - paper on HTTP GUIDs sent.

**Comment by jholetschek** [comment]
Apparently the dataset is accessible since April 2018: https://www.gbif.org/dataset/f0c74a2c-4bd8-49d0-837a-92bb835fd2f3. BioCASe web service is working and harvested regularly.
