### ISSUE TITLE
Herbário da Pontifícia Universidade Católica do Paraná - HUCP

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/data-mobilization#30]
A data paper describing IPT dataset not in GBIF

http://www.mdpi.com/2306-5729/2/1/10/htm
describes
https://ferramentas.sibbr.gov.br/parceiros_jbrj/resource?r=hucp_5

which isn't registered with GBIF (but might be included in a larger dataset previously published)

**Comment by kbraak** [comment]
Dear Eduardo @edalcin,
Dear David @dvdscripter,

My colleague recently came across a set of datasets published in the ['parceiros_jbrj IPT'](https://ferramentas.sibbr.gov.br/parceiros_jbrj/resource?r=hucp_5) This IPT isn't registered with GBIF nor is it listed in [Brazil's IPTs](http://www.sibbr.gov.br/areas/index.php?area=publicar&subarea=lista-dos-ipts). The reason we came across is, it because [this data paper](http://www.mdpi.com/2306-5729/2/1/10/htm) references one of its datasets. 

If possible, would either of you please be able to describe this IPT and whether its datasets are going to be or have already been published through GBIF? Thanks for your kind assistance. 

#### Screenshots:

<img width="657" alt="screen shot 2017-03-07 at 17 16 50" src="https://cloud.githubusercontent.com/assets/5981100/23666426/49805634-035b-11e7-8981-c1068309a90d.png">

---
<img width="1194" alt="screen shot 2017-03-07 at 17 23 37" src="https://cloud.githubusercontent.com/assets/5981100/23666432/4c926268-035b-11e7-906c-e3ecf1ad4f55.png">

**Comment by dvdscripter** [comment]
Hi Kyle,

This IPT only receive publication from our internal software and was hidden
in plain sight from users.
Which the above publication I'll request to let this instance be public and
registered at GBIF Brazilian IPT list.

Thanks for calling our attention on the matter

2017-03-07 13:32 GMT-03:00 Kyle Braak <notifications@github.com>:

**Comment by kbraak** [comment]
Dear David, Thank you for your reply - that sounds great.

**Comment by dnoesgaard** [comment]
Updating our list of recently published data papers, I came across this one again, and noticed that the [dataset](https://ferramentas.sibbr.gov.br/parceiros_jbrj/resource?r=hucp_5) still isn't registered. I don't know if this is an oversight?

**Comment by dvdscripter** [comment]
Sadly no resource at this IPT will be registered at gbif. These resources will gain an associated media from JBRJ publisher and republished at their infra.

**Comment by ahahn-gbif** [comment]
Registered and indexed in May 2020: https://ipt.sibbr.gov.br/parceiros_jbrj/resource?r=hucp_5 / https://www.gbif.org/dataset/aeb4640c-e649-43b9-bf5c-dc9c6ec7540e (via SiBBr) - closing
