### ISSUE TITLE
Complete data from the Barro Colorado 50-ha plot: 423617 trees, 35 years

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/data-mobilization#352]
**Dataset link**: https://datadryad.org/stash/dataset/doi:10.15146/5xcp-0d46

**Region**: Panama

**Taxon**: Plants

**Type**: Sampling Event

**Why is this important**: historical repeated sampling

**Priority**: 

**Comments**: I discovered this dataset from [this article](https://www.quantamagazine.org/the-key-to-species-diversity-may-be-in-their-similarities-20230626/?mc_cid=c5ba5426dc&mc_eid=80c23c6dd3)

**Dataholders contact information**: 

**Users contact info**:

**Comment by sformel-usgs** [comment]
We received a _very_ emphatic no from Richard Condit about these datasets:

https://datadryad.org/stash/dataset/doi:10.15146/5xcp-0d46
https://datadryad.org/stash/dataset/doi:10.15146/R3FH61
https://datadryad.org/stash/dataset/doi:10.15146/mdpr-pm59

It's confusing because they have applied the default Dryad CC0 license to all three datasets, but then try to place restrictions on the data through the abstract. Richard made it extremely clear he was not interested in discussing it or learning anything more about GBIF.
