### ISSUE TITLE
European Lake Fishes Dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#40]
## European Lake Fishes Dataset

Region: Europe

Taxon: Freshwater fish

Type: sampling event

License: Not open

Bibliographic reference: https://doi.org/10.15504/fmj.2017.23

Comments: Here&#39;s another example of a compilation of national datasets (it seems). In the metadata paper it is stated that the dataset has NOT been published with GBIF, although &quot;exchange&quot; is &quot;planned&quot;(?).

Users contact info: dnoesgaard@gbif.org

**Comment by kcopas** [comment]
Wanted to note that outstanding issues remain with earlier Biofresh datasets. Unclear whether this is accidental or intentional: see both [GBIF.org publisher page](http://www.gbif.org/publisher/b872b075-9ab5-4e27-b6c6-5add6b890379) and [late 2015 JIRA issue](http://dev.gbif.org/issues/browse/DM-278)

**Comment by dschigel** [comment]
I recall some TDWG 2016 news on Biofresh - can help dig out those notes once someone starts working on publication

**Comment by ahahn-gbif** [comment]
BioFresh is a registered publisher (https://www.gbif.org/publisher/b872b075-9ab5-4e27-b6c6-5add6b890379) with 39 datasets. Coordinator for the Freshwater Network (https://www.gbif.org/network/d1627240-04ab-4162-aee9-b16df6bc8308). Closing
